name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: macos-latest-xl

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
   
      - name: Install packages
        run: |
              npm ci            
      - name: Build code
        run: |
              npm run build
              npm run test